#!/work/apps/tools/conda/minconda3/20230202/bin/Rscript

## 找出两个区间的重合段，并输出新的区间文件

# setwd(dir)
default_warn <- getOption("warn") ## 隐藏警告信息
library(data.table, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(getopt, warn.conflicts = FALSE)
options(warn = default_warn) ## 恢复警告信息显示

## 命令行参数
spec <- matrix(
  c(
    "bin1", "1", 2, "character", "[Required] eigenvector file generated by Plink",
    "bin2", "2", 2, "character", "[Required] populations/group names",
    "out",  "O", 2, "character", "[Optional] output result prefix",
    "help", "h", 0, "logical",   "This is Help!"
  ),
  byrow = TRUE, ncol = 5
)
opt <- getopt(spec = spec)

## 检查参数
if (!is.null(opt$help) || is.null(opt$bin1) || is.null(opt$bin2)) {
  cat(paste(getopt(spec = spec, usage = TRUE), "\n"))
  quit()
}

## 默认参数
if (is.null(opt$out)) opt$out <- "new_bin.txt"

## 检查文件是否存在
if (!file.exists(opt$bin1) || !file.exists(opt$bin2)) {
  cat(paste0(opt$bin1, "or", opt$bin2, "not found!\n"))
  quit()
}


bin1 <- fread(opt$bin1)
bin2 <- fread(opt$bin2)

bin <- data.frame(index = 1:sum(bin1$nSNP),
                  bin1 = rep(seq_len(nrow(bin1)), times = bin1$nSNP),
                  bin2 = rep(seq_len(nrow(bin2)), times = bin2$nSNP))

## 使用dplyr包进行分组和计算新的区间编号
result <- bin %>%
  group_by(bin1, bin2) %>%
  mutate(bin3 = cur_group_id())

## 生成区间内SNP数的文件
new_bin <- table(as.factor(result$bin3))

## 写出文件
write.table(as.vector(new_bin), opt$out, row.names = FALSE, col.names = FALSE, quote = FALSE)
cat(paste0("new bin file output to: ", opt$out, "\n"))

## debug
opt=list()
opt$bin1="/work/home/ljfgroup01/WORKSPACE/liwn/mbGS/QMSim/Two/rep11/cubic_A_50_psim.txt"
opt$bin2="/work/home/ljfgroup01/WORKSPACE/liwn/mbGS/QMSim/Two/rep11/cubic_B_50_psim.txt"
opt$out="/work/home/ljfgroup01/WORKSPACE/liwn/mbGS/QMSim/Two/rep11/cubic_overlap_50_psim.txt"
