#!/work/apps/tools/conda/minconda3/20230202/bin/Rscript

## 根据plink特征向量结果进行 PCA 作图
## 输入文件：plink生成的主成分分析结果文件*.eigenvec，前4列需要为FID、IID、PC1、PC2

# setwd(dir)
default_warn <- getOption("warn") ## 隐藏警告信息
library(Cairo, warn.conflicts = FALSE)
library(ggplot2, warn.conflicts = FALSE)
library(getopt, warn.conflicts = FALSE)
options(warn = default_warn) ## 恢复警告信息显示

## 命令行参数
spec <- matrix(
  c(
    "eigv",  "I", 2, "character", "[Required] eigenvector file generated by Plink",
    "group", "G", 2, "character", "[Optional] populations/group names",
    "out",   "O", 2, "character", "[Optional] output result prefix",
    "help",  "h", 0, "logical",   "This is Help!"
  ),
  byrow = TRUE, ncol = 5
)
opt <- getopt(spec = spec)

## 检查参数
if (!is.null(opt$help) || is.null(opt$eigv)) {
  cat(paste(getopt(spec = spec, usage = TRUE), "\n"))
  quit()
}

## plink计算的PCA结果
pca <- read.table(opt$eigv, header = TRUE)

## 检查pca结果文件是否存在标题
if (names(pca)[1] != "FID") {
  pca <- read.table(opt$eigv, header = FALSE)
  names(pca)[1:4] <- c("IID", "FID", "PC1", "PC2")
}

## 分组信息
if (is.null(opt$group)) {
  if (identical(pca$FID, pca$IID)) {
    if (ncol(pca) > 5) {
      names(pca)[6] <- c("group")
    } else {
      cat("Please provide the IID-FID match file.")
      quit()
    }
  } else {
    names(pca)[which(names(pca) == "FID")] <- "group"
  }
} else {
  group <- read.table(opt$group, header = TRUE)
  names(group) <- c("IID", "group")
  pca <- merge(pca, group, by = "IID")
}

## 文件名
if (is.null(opt$out)) {
  output <- paste0("PCA_", unique(pca$group)[1], "_", unique(pca$group)[2], ".png")
} else {
  output <- paste0(opt$out, ".png")
}

## 根据主成分1和2作图
# png(output, width = 800, height = 600, bg = "white")
CairoPNG(output, width = 800, height = 600, bg = "white")

ggplot(pca, aes(x = PC1, y = PC2, colour = group, shape = group)) +
  geom_point(size = 1.5) +
  theme(
    axis.text.x = element_text(colour = "black", size = 14),
    axis.text.y = element_text(size = 14, face = "plain"),
    axis.title.x = element_text(size = 14, face = "plain"),
    axis.title.y = element_text(size = 14, face = "plain"),
    legend.text = element_text(size = 26),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  xlab("Principal component 1") +
  ylab("Principal component 2")

hide_message <- dev.off()
cat("PCA plot successfully.\n")
